service:
  name: target detection
  port: 5000
  tags: 
    - interface:gRPC
    - algorithm:YOLOv5
  weight_info_folder: /workspace/weights_info
  weights_folder: /workspace/weights

consul:
  ip: 10.10.10.2
  port: 8500